// Package intra provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package intraoapi42

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CloseResponseKind.
const (
	CloseResponseKindAgu               CloseResponseKind = "agu"
	CloseResponseKindBlackHole         CloseResponseKind = "black_hole"
	CloseResponseKindDeserter          CloseResponseKind = "deserter"
	CloseResponseKindNonAdmitted       CloseResponseKind = "non_admitted"
	CloseResponseKindOther             CloseResponseKind = "other"
	CloseResponseKindPaceUnknown       CloseResponseKind = "pace_unknown"
	CloseResponseKindSeriousMisconduct CloseResponseKind = "serious_misconduct"
	CloseResponseKindSocialSecurity    CloseResponseKind = "social_security"
)

// Valid indicates whether the value is a known member of the CloseResponseKind enum.
func (e CloseResponseKind) Valid() bool {
	switch e {
	case CloseResponseKindAgu:
		return true
	case CloseResponseKindBlackHole:
		return true
	case CloseResponseKindDeserter:
		return true
	case CloseResponseKindNonAdmitted:
		return true
	case CloseResponseKindOther:
		return true
	case CloseResponseKindPaceUnknown:
		return true
	case CloseResponseKindSeriousMisconduct:
		return true
	case CloseResponseKindSocialSecurity:
		return true
	default:
		return false
	}
}

// Defines values for LightUserResponseKind.
const (
	LightUserResponseKindAdmin    LightUserResponseKind = "admin"
	LightUserResponseKindExternal LightUserResponseKind = "external"
	LightUserResponseKindStudent  LightUserResponseKind = "student"
)

// Valid indicates whether the value is a known member of the LightUserResponseKind enum.
func (e LightUserResponseKind) Valid() bool {
	switch e {
	case LightUserResponseKindAdmin:
		return true
	case LightUserResponseKindExternal:
		return true
	case LightUserResponseKindStudent:
		return true
	default:
		return false
	}
}

// Defines values for UserCandidatureResponseGender.
const (
	UserCandidatureResponseGenderFemale UserCandidatureResponseGender = "female"
	UserCandidatureResponseGenderMale   UserCandidatureResponseGender = "male"
	UserCandidatureResponseGenderOther  UserCandidatureResponseGender = "other"
)

// Valid indicates whether the value is a known member of the UserCandidatureResponseGender enum.
func (e UserCandidatureResponseGender) Valid() bool {
	switch e {
	case UserCandidatureResponseGenderFemale:
		return true
	case UserCandidatureResponseGenderMale:
		return true
	case UserCandidatureResponseGenderOther:
		return true
	default:
		return false
	}
}

// Defines values for UserResponseKind.
const (
	UserResponseKindAdmin    UserResponseKind = "admin"
	UserResponseKindExternal UserResponseKind = "external"
	UserResponseKindStudent  UserResponseKind = "student"
)

// Valid indicates whether the value is a known member of the UserResponseKind enum.
func (e UserResponseKind) Valid() bool {
	switch e {
	case UserResponseKindAdmin:
		return true
	case UserResponseKindExternal:
		return true
	case UserResponseKindStudent:
		return true
	default:
		return false
	}
}

// Defines values for GetClosesParamsSort.
const (
	CloserId  GetClosesParamsSort = "closer_id"
	CreatedAt GetClosesParamsSort = "created_at"
	EndAt     GetClosesParamsSort = "end_at"
	Id        GetClosesParamsSort = "id"
	Jid       GetClosesParamsSort = "jid"
	Kind      GetClosesParamsSort = "kind"
	Reason    GetClosesParamsSort = "reason"
	State     GetClosesParamsSort = "state"
	UpdatedAt GetClosesParamsSort = "updated_at"
	UserId    GetClosesParamsSort = "user_id"
)

// Valid indicates whether the value is a known member of the GetClosesParamsSort enum.
func (e GetClosesParamsSort) Valid() bool {
	switch e {
	case CloserId:
		return true
	case CreatedAt:
		return true
	case EndAt:
		return true
	case Id:
		return true
	case Jid:
		return true
	case Kind:
		return true
	case Reason:
		return true
	case State:
		return true
	case UpdatedAt:
		return true
	case UserId:
		return true
	default:
		return false
	}
}

// AchievementResponse defines model for AchievementResponse.
type AchievementResponse struct {
	Description  string `json:"description"`
	Id           int    `json:"id"`
	Image        string `json:"image"`
	Kind         string `json:"kind"`
	Name         string `json:"name"`
	NbrOfSuccess *int   `json:"nbr_of_success,omitempty"`
	Tier         string `json:"tier"`
	UsersUrl     string `json:"users_url"`
	Visible      bool   `json:"visible"`
}

// CampusResponse defines model for CampusResponse.
type CampusResponse struct {
	Active             bool              `json:"active"`
	Address            *string           `json:"address,omitempty"`
	City               string            `json:"city"`
	Country            string            `json:"country"`
	DefaultHiddenPhone *bool             `json:"default_hidden_phone,omitempty"`
	EmailExtension     string            `json:"email_extension"`
	Facebook           *string           `json:"facebook,omitempty"`
	Id                 int               `json:"id"`
	Language           *LanguageResponse `json:"language,omitempty"`
	Name               string            `json:"name"`
	Public             bool              `json:"public"`
	TimeZone           string            `json:"time_zone"`
	Twitter            *string           `json:"twitter,omitempty"`
	UsersCount         int               `json:"users_count"`
	VogsphereId        int               `json:"vogsphere_id"`
	Website            *string           `json:"website,omitempty"`
	Zip                *string           `json:"zip,omitempty"`
}

// CampusUserResponse defines model for CampusUserResponse.
type CampusUserResponse struct {
	CampusId  int       `json:"campus_id"`
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	IsPrimary bool      `json:"is_primary"`
	UpdatedAt time.Time `json:"updated_at"`
	UserId    int       `json:"user_id"`
}

// CloseResponse defines model for CloseResponse.
type CloseResponse struct {
	// Closer Example: {"active":true,"alumni?":false,"alumnized_at":null,"anonymize_date":"2025-10-24T00:00:00.000+02:00","correction_point":4,"created_at":"2018-07-17T08:57:33.128Z","data_erasure_date":"2025-10-24T00:00:00.000+02:00","displayname":"Malo Allain","email":"malallai@student.42.fr","first_name":"Malo","id":39962,"image":{"link":"https://cdn.intra.42.fr/users/39a641ed152b654cfbff5c5864eb05c1/malallai.jpg","versions":{"large":"https://cdn.intra.42.fr/users/a818d7a54298d333411557d0b55b61b3/large_malallai.jpg","medium":"https://cdn.intra.42.fr/users/53691acd1e0ea75b782ddbe121c17423/medium_malallai.jpg","micro":"https://cdn.intra.42.fr/users/6f74b46e2016b0e6c41fa05b5952e17c/micro_malallai.jpg","small":"https://cdn.intra.42.fr/users/617de91b59fd7e59ecaf6470a4b37645/small_malallai.jpg"}},"kind":"student","last_name":"Allain","location":null,"login":"malallai","phone":"hidden","pool_month":"august","pool_year":"2018","staff":false,"updated_at":"2022-09-27T18:48:28.207Z","url":"https://api.intra.42.fr/v2/users/malallai","usual_first_name":null,"usual_full_name":"Malo Allain","wallet":290}
	Closer            LightUserResponse          `json:"closer"`
	CommunityServices []CommunityServiceResponse `json:"community_services"`
	CreatedAt         time.Time                  `json:"created_at"`
	EndAt             *time.Time                 `json:"end_at,omitempty"`
	Id                int                        `json:"id"`
	Kind              CloseResponseKind          `json:"kind"`
	Reason            string                     `json:"reason"`
	State             string                     `json:"state"`
	UpdatedAt         time.Time                  `json:"updated_at"`

	// User Example: {"active":true,"alumni?":false,"alumnized_at":null,"anonymize_date":"2025-10-24T00:00:00.000+02:00","correction_point":4,"created_at":"2018-07-17T08:57:33.128Z","data_erasure_date":"2025-10-24T00:00:00.000+02:00","displayname":"Malo Allain","email":"malallai@student.42.fr","first_name":"Malo","id":39962,"image":{"link":"https://cdn.intra.42.fr/users/39a641ed152b654cfbff5c5864eb05c1/malallai.jpg","versions":{"large":"https://cdn.intra.42.fr/users/a818d7a54298d333411557d0b55b61b3/large_malallai.jpg","medium":"https://cdn.intra.42.fr/users/53691acd1e0ea75b782ddbe121c17423/medium_malallai.jpg","micro":"https://cdn.intra.42.fr/users/6f74b46e2016b0e6c41fa05b5952e17c/micro_malallai.jpg","small":"https://cdn.intra.42.fr/users/617de91b59fd7e59ecaf6470a4b37645/small_malallai.jpg"}},"kind":"student","last_name":"Allain","location":null,"login":"malallai","phone":"hidden","pool_month":"august","pool_year":"2018","staff":false,"updated_at":"2022-09-27T18:48:28.207Z","url":"https://api.intra.42.fr/v2/users/malallai","usual_first_name":null,"usual_full_name":"Malo Allain","wallet":290}
	User LightUserResponse `json:"user"`
}

// CloseResponseKind defines model for CloseResponse.Kind.
type CloseResponseKind string

// CommunityServiceResponse defines model for CommunityServiceResponse.
type CommunityServiceResponse struct {
	CreatedAt  time.Time `json:"created_at"`
	Duration   int       `json:"duration"`
	Id         int       `json:"id"`
	Occupation string    `json:"occupation"`
	ScheduleAt time.Time `json:"schedule_at"`
	State      string    `json:"state"`
	UpdatedAt  *string   `json:"updated_at,omitempty"`
}

// CursusResponse defines model for CursusResponse.
type CursusResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	Kind      string    `json:"kind"`
	Name      string    `json:"name"`
	Slug      string    `json:"slug"`
}

// CursusUserResponse defines model for CursusUserResponse.
type CursusUserResponse struct {
	BeginAt      time.Time       `json:"begin_at"`
	BlackholedAt *time.Time      `json:"blackholed_at,omitempty"`
	CreatedAt    time.Time       `json:"created_at"`
	Cursus       CursusResponse  `json:"cursus"`
	CursusId     int             `json:"cursus_id"`
	EndAt        *time.Time      `json:"end_at,omitempty"`
	Grade        string          `json:"grade"`
	HasCoalition bool            `json:"has_coalition"`
	Id           int             `json:"id"`
	Level        float64         `json:"level"`
	Skills       []SkillResponse `json:"skills"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

// Error Example: {"error":"The access token is invalid","status":401}
type Error struct {
	// Error Error message
	Error string `json:"error"`

	// Status HTTP status code
	Status int `json:"status"`
}

// GroupResponse defines model for GroupResponse.
type GroupResponse struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// IntraDateTime Example: 2017-03-25T13:30:00.000Z
type IntraDateTime = IntraTime

// LanguageResponse defines model for LanguageResponse.
type LanguageResponse struct {
	CreatedAt  time.Time `json:"created_at"`
	Id         int       `json:"id"`
	Identifier string    `json:"identifier"`
	Name       string    `json:"name"`
	UpdatedAt  time.Time `json:"updated_at"`
}

// LanguageUserResponse defines model for LanguageUserResponse.
type LanguageUserResponse struct {
	CreatedAt  time.Time `json:"created_at"`
	Id         int       `json:"id"`
	LanguageId int       `json:"language_id"`
	Position   int       `json:"position"`
	UserId     int       `json:"user_id"`
}

// LightUserResponse Example: {"active":true,"alumni?":false,"alumnized_at":null,"anonymize_date":"2025-10-24T00:00:00.000+02:00","correction_point":4,"created_at":"2018-07-17T08:57:33.128Z","data_erasure_date":"2025-10-24T00:00:00.000+02:00","displayname":"Malo Allain","email":"malallai@student.42.fr","first_name":"Malo","id":39962,"image":{"link":"https://cdn.intra.42.fr/users/39a641ed152b654cfbff5c5864eb05c1/malallai.jpg","versions":{"large":"https://cdn.intra.42.fr/users/a818d7a54298d333411557d0b55b61b3/large_malallai.jpg","medium":"https://cdn.intra.42.fr/users/53691acd1e0ea75b782ddbe121c17423/medium_malallai.jpg","micro":"https://cdn.intra.42.fr/users/6f74b46e2016b0e6c41fa05b5952e17c/micro_malallai.jpg","small":"https://cdn.intra.42.fr/users/617de91b59fd7e59ecaf6470a4b37645/small_malallai.jpg"}},"kind":"student","last_name":"Allain","location":null,"login":"malallai","phone":"hidden","pool_month":"august","pool_year":"2018","staff":false,"updated_at":"2022-09-27T18:48:28.207Z","url":"https://api.intra.42.fr/v2/users/malallai","usual_first_name":null,"usual_full_name":"Malo Allain","wallet":290}
type LightUserResponse struct {
	// Active Indicates if the user is active.
	Active bool `json:"active"`

	// Alumni Indicates if the user is an alumnus.
	Alumni bool `json:"alumni?"`

	// AlumnizedAt The date when the user became an alumnus.
	AlumnizedAt *time.Time `json:"alumnized_at,omitempty"`

	// AnonymizeDate The date when user data will be anonymized.
	AnonymizeDate time.Time `json:"anonymize_date"`

	// CorrectionPoint The user's correction points.
	CorrectionPoint int `json:"correction_point"`

	// CreatedAt The user creation timestamp.
	CreatedAt time.Time `json:"created_at"`

	// DataErasureDate The date when user data will be erased.
	DataErasureDate time.Time `json:"data_erasure_date"`

	// Displayname The display name of the user.
	Displayname string `json:"displayname"`

	// Email The email address of the user.
	Email string `json:"email"`

	// FirstName The first name of the user.
	FirstName string `json:"first_name"`

	// Id The unique identifier of the user.
	Id    int                `json:"id"`
	Image *UserImageResponse `json:"image,omitempty"`

	// Kind The kind of user (e.g., student, admin, external).
	Kind LightUserResponseKind `json:"kind"`

	// LastName The last name of the user.
	LastName string `json:"last_name"`

	// Location The location of the user.
	Location *string `json:"location,omitempty"`

	// Login The login name of the user.
	Login string `json:"login"`

	// Phone The phone number of the user (always hidden).
	Phone *string `json:"phone,omitempty"`

	// PoolMonth The month of the user's pool.
	PoolMonth string `json:"pool_month"`

	// PoolYear The year of the user's pool.
	PoolYear string `json:"pool_year"`

	// Staff Indicates if the user is staff.
	Staff *bool `json:"staff?,omitempty"`

	// UpdatedAt The last user update timestamp.
	UpdatedAt time.Time `json:"updated_at"`

	// Url The URL to the user's resource.
	Url string `json:"url"`

	// UsualFirstName The usual first name of the user, first_name if none.
	UsualFirstName *string `json:"usual_first_name,omitempty"`

	// UsualFullName The usual full name of the user, usually usual_first_name or first_name + last_name.
	UsualFullName string `json:"usual_full_name"`

	// Wallet The user's wallet balance.
	Wallet int `json:"wallet"`
}

// LightUserResponseKind The kind of user (e.g., student, admin, external).
type LightUserResponseKind string

// PatronageResponse defines model for PatronageResponse.
type PatronageResponse struct {
	CreatedAt   time.Time `json:"created_at"`
	GodfatherId *int      `json:"godfather_id,omitempty"`
	GodsonId    *int      `json:"godson_id,omitempty"`
	Id          int       `json:"id"`
	Ongoing     bool      `json:"ongoing"`
	UpdatedAt   time.Time `json:"updated_at"`
	UserId      *int      `json:"user_id,omitempty"`
}

// ProjectLightResponse defines model for ProjectLightResponse.
type ProjectLightResponse struct {
	Id       int    `json:"id"`
	Name     string `json:"name"`
	ParentId *int   `json:"parent_id,omitempty"`
	Slug     string `json:"slug"`
}

// ProjectUserResponse defines model for ProjectUserResponse.
type ProjectUserResponse struct {
	CreatedAt     time.Time             `json:"created_at"`
	CurrentTeamId *int                  `json:"current_team_id,omitempty"`
	CursusIds     []int                 `json:"cursus_ids"`
	FinalMark     *int                  `json:"final_mark,omitempty"`
	Id            int                   `json:"id"`
	Marked        bool                  `json:"marked"`
	MarkedAt      *time.Time            `json:"marked_at,omitempty"`
	Occurrence    int                   `json:"occurrence"`
	Project       *ProjectLightResponse `json:"project,omitempty"`
	RetriableAt   *time.Time            `json:"retriable_at,omitempty"`
	Status        string                `json:"status"`
	UpdatedAt     time.Time             `json:"updated_at"`
	Validated     *bool                 `json:"validated,omitempty"`
}

// RoleResponse defines model for RoleResponse.
type RoleResponse struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// SkillResponse defines model for SkillResponse.
type SkillResponse struct {
	Id    int     `json:"id"`
	Level float64 `json:"level"`
	Name  string  `json:"name"`
}

// TitleResponse defines model for TitleResponse.
type TitleResponse struct {
	Id   int    `json:"id"`
	Name string `json:"name"`
}

// TitleUserResponse defines model for TitleUserResponse.
type TitleUserResponse struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int       `json:"id"`
	Selected  bool      `json:"selected"`
	TitleId   int       `json:"title_id"`
	UpdatedAt time.Time `json:"updated_at"`
	UserId    int       `json:"user_id"`
}

// UserCandidatureResponse Example: {"birth_city":"Paris","birth_country":"France","birth_date":"2013-01-01","contact_affiliation":"Parent","contact_first_name":"Norminette","contact_last_name":"Moulinette","contact_phone1":"+33600000000","contact_phone2":null,"country":"France","created_at":"2020-08-27T07:31:49.431Z","email":"tmatis@example.com","gender":"male","hidden_phone":false,"id":42,"language":"fr","max_level_logic":null,"max_level_memory":null,"meeting_date":null,"other_information":null,"phone":"+33600000000","phone_country_code":"FR","pin":"7777","piscine_date":null,"postal_city":"Paris","postal_complement":null,"postal_country":"France","postal_street":"96 boulevard Bessières","postal_zip_code":"75017","updated_at":"2025-07-10T16:16:34.238Z","user_id":42,"zip_code":"75017"}
type UserCandidatureResponse struct {
	BirthCity          string                         `json:"birth_city"`
	BirthCountry       *string                        `json:"birth_country,omitempty"`
	BirthDate          *openapi_types.Date            `json:"birth_date,omitempty"`
	ContactAffiliation string                         `json:"contact_affiliation"`
	ContactFirstName   string                         `json:"contact_first_name"`
	ContactLastName    string                         `json:"contact_last_name"`
	ContactPhone1      string                         `json:"contact_phone1"`
	ContactPhone2      *string                        `json:"contact_phone2,omitempty"`
	Country            *string                        `json:"country,omitempty"`
	CreatedAt          time.Time                      `json:"created_at"`
	Email              string                         `json:"email"`
	Gender             *UserCandidatureResponseGender `json:"gender,omitempty"`
	HiddenPhone        bool                           `json:"hidden_phone"`
	Id                 int                            `json:"id"`
	Language           string                         `json:"language"`
	MaxLevelLogic      *float64                       `json:"max_level_logic,omitempty"`
	MaxLevelMemory     *float64                       `json:"max_level_memory,omitempty"`
	MeetingDate        *IntraDateTime                 `json:"meeting_date,omitempty"`
	OtherInformation   *string                        `json:"other_information,omitempty"`
	Phone              string                         `json:"phone"`
	PhoneCountryCode   string                         `json:"phone_country_code"`
	Pin                string                         `json:"pin"`
	PiscineDate        *IntraDateTime                 `json:"piscine_date,omitempty"`
	PostalCity         string                         `json:"postal_city"`
	PostalComplement   *string                        `json:"postal_complement,omitempty"`
	PostalCountry      string                         `json:"postal_country"`
	PostalStreet       string                         `json:"postal_street"`
	PostalZipCode      string                         `json:"postal_zip_code"`
	UpdatedAt          time.Time                      `json:"updated_at"`
	UserId             int                            `json:"user_id"`
	ZipCode            *string                        `json:"zip_code,omitempty"`
}

// UserCandidatureResponseGender defines model for UserCandidatureResponse.Gender.
type UserCandidatureResponseGender string

// UserImageResponse defines model for UserImageResponse.
type UserImageResponse struct {
	// Link The URL to the user's image.
	Link     string `json:"link"`
	Versions struct {
		// Large URL to the large version of the user's image.
		Large string `json:"large"`

		// Medium URL to the medium version of the user's image.
		Medium string `json:"medium"`

		// Micro URL to the micro version of the user's image.
		Micro string `json:"micro"`

		// Small URL to the small version of the user's image.
		Small string `json:"small"`
	} `json:"versions"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Achievements []AchievementResponse `json:"achievements"`

	// Active Indicates if the user is active.
	Active bool `json:"active"`

	// Alumni Indicates if the user is an alumnus.
	Alumni bool `json:"alumni?"`

	// AlumnizedAt The date when the user became an alumnus.
	AlumnizedAt *time.Time `json:"alumnized_at,omitempty"`

	// AnonymizeDate The date when user data will be anonymized.
	AnonymizeDate time.Time            `json:"anonymize_date"`
	Campus        []CampusResponse     `json:"campus"`
	CampusUsers   []CampusUserResponse `json:"campus_users"`

	// CorrectionPoint The user's correction points.
	CorrectionPoint int `json:"correction_point"`

	// CreatedAt The user creation timestamp.
	CreatedAt   time.Time            `json:"created_at"`
	CursusUsers []CursusUserResponse `json:"cursus_users"`

	// DataErasureDate The date when user data will be erased.
	DataErasureDate time.Time `json:"data_erasure_date"`

	// Displayname The display name of the user.
	Displayname string `json:"displayname"`

	// Email The email address of the user.
	Email string `json:"email"`

	// FirstName The first name of the user.
	FirstName string          `json:"first_name"`
	Groups    []GroupResponse `json:"groups"`

	// Id The unique identifier of the user.
	Id    int                `json:"id"`
	Image *UserImageResponse `json:"image,omitempty"`

	// Kind The kind of user (e.g., student, admin, external).
	Kind           UserResponseKind       `json:"kind"`
	LanguagesUsers []LanguageUserResponse `json:"languages_users"`

	// LastName The last name of the user.
	LastName string `json:"last_name"`

	// Location The location of the user.
	Location *string `json:"location,omitempty"`

	// Login The login name of the user.
	Login     string              `json:"login"`
	Patroned  []PatronageResponse `json:"patroned"`
	Patroning []PatronageResponse `json:"patroning"`

	// Phone The phone number of the user (always hidden).
	Phone *string `json:"phone,omitempty"`

	// PoolMonth The month of the user's pool.
	PoolMonth string `json:"pool_month"`

	// PoolYear The year of the user's pool.
	PoolYear      string                `json:"pool_year"`
	ProjectsUsers []ProjectUserResponse `json:"projects_users"`
	Roles         []RoleResponse        `json:"roles"`

	// Staff Indicates if the user is staff.
	Staff       *bool               `json:"staff?,omitempty"`
	Titles      []TitleResponse     `json:"titles"`
	TitlesUsers []TitleUserResponse `json:"titles_users"`

	// UpdatedAt The last user update timestamp.
	UpdatedAt time.Time `json:"updated_at"`

	// Url The URL to the user's resource.
	Url string `json:"url"`

	// UsualFirstName The usual first name of the user, first_name if none.
	UsualFirstName *string `json:"usual_first_name,omitempty"`

	// UsualFullName The usual full name of the user, usually usual_first_name or first_name + last_name.
	UsualFullName string `json:"usual_full_name"`

	// Wallet The user's wallet balance.
	Wallet int `json:"wallet"`
}

// UserResponseKind The kind of user (e.g., student, admin, external).
type UserResponseKind string

// Page defines model for page.
type Page = int

// PageNumber defines model for page_number.
type PageNumber = int

// PageSize defines model for page_size.
type PageSize = int

// PerPage defines model for per_page.
type PerPage = int

// ErrorResponse Example: {"error":"The access token is invalid","status":401}
type ErrorResponse = Error

// GetClosesParams defines parameters for GetCloses.
type GetClosesParams struct {
	// Sort The sort field. Sorted by created_at desc, id desc by default.
	// Must be one of: id, user_id, closer_id, reason, state, created_at, updated_at, kind, end_at, jid.
	Sort *GetClosesParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// Filter Filtering on one or more fields. Must be one of: id, user_id, closer_id, reason, state, created_at, updated_at, kind, end_at, jid, campus_id, end.
	Filter *map[string]string `json:"filter,omitempty"`

	// Range Select on a particular range. Must be one of: id, user_id, closer_id, reason, state, created_at, updated_at, kind, end_at, jid.
	Range *map[string]string `json:"range,omitempty"`

	// Page Page number (1-based). The 42 API paginates index endpoints and defaults to 30 items per page.
	// You can also use the `per_page` parameter to set the page size (up to 100 for many endpoints).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Maximum is generally 100 but some endpoints limit this for technical reasons.
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// PageNumber Alternate pagination style using `page[number]` (1-based page index). Can be used together with `page[size]`.
	PageNumber *PageNumber `form:"page[number],omitempty" json:"page[number],omitempty"`

	// PageSize Alternate pagination style to set the page size (maximum depends on endpoint, commonly up to 100).
	PageSize *PageSize `form:"page[size],omitempty" json:"page[size],omitempty"`
}

// GetClosesParamsSort defines parameters for GetCloses.
type GetClosesParamsSort string

// GetUsersParams defines parameters for GetUsers.
type GetUsersParams struct {
	// Sort The sort field. Sorted by id desc by default.
	// Must be one of: id, login, email, encrypted_password, reset_password_token, reset_password_sent_at, created_at, updated_at, image, first_name, last_name, pool_year, pool_month, kind, status, otp_secret_key, otp_tmp, otp_activated, otp_backup_passwords, slack_team, slack_login, slack_mail, slack_code_validation, slack_validated_at, token_id, email_stop, linked_user_id, usual_first_name, last_seen_at, password_changed_at, encrypted_single_usage_password, first_warn_anon_sent_at, second_warn_anon_sent_at, alumnized_at, anonymized_at.
	// Example: -alumnized_at,anonymized_at (to sort on alumnized_at descending and anonymized_at ascending)
	Sort *string `form:"sort,omitempty" json:"sort,omitempty"`

	// Filter Filtering on one or more fields.
	// Must be one of: id, login, email, created_at, updated_at, pool_year, pool_month, kind, status, primary_campus_id, first_name, last_name, alumni?, staff?.
	// Example: filter[id]=a_value,another_value (to filter on users with id matching a_value or another_value)
	Filter *map[string]string `json:"filter,omitempty"`

	// Range Select on a particular range.
	// Must be one of: id, login, email, created_at, updated_at, pool_year, pool_month, kind, status.
	// Example: range[status]=min_value,max_value (to range on users with status field between min_value and max_value)
	Range *map[string]string `json:"range,omitempty"`

	// Page Page number (1-based). The 42 API paginates index endpoints and defaults to 30 items per page.
	// You can also use the `per_page` parameter to set the page size (up to 100 for many endpoints).
	Page *Page `form:"page,omitempty" json:"page,omitempty"`

	// PerPage Number of items per page. Maximum is generally 100 but some endpoints limit this for technical reasons.
	PerPage *PerPage `form:"per_page,omitempty" json:"per_page,omitempty"`

	// PageNumber Alternate pagination style using `page[number]` (1-based page index). Can be used together with `page[size]`.
	PageNumber *PageNumber `form:"page[number],omitempty" json:"page[number],omitempty"`

	// PageSize Alternate pagination style to set the page size (maximum depends on endpoint, commonly up to 100).
	PageSize *PageSize `form:"page[size],omitempty" json:"page[size],omitempty"`
}

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// GetCloses Get a list of closes
	//
	// Corresponds with GET /closes (the `GetCloses` operationId).
	GetCloses(ctx context.Context, params *GetClosesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetLanguageById Get a language by ID
	//
	// Corresponds with GET /languages/{id} (the `GetLanguageById` operationId).
	GetLanguageById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUsers Get a list of users
	//
	// Corresponds with GET /users (the `GetUsers` operationId).
	GetUsers(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserById Get a user by ID
	//
	// Corresponds with GET /users/{id} (the `GetUserById` operationId).
	GetUserById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetUserCandidatureById Get user candidature information
	//
	// Corresponds with GET /users/{id}/user_candidature (the `GetUserCandidatureById` operationId).
	GetUserCandidatureById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// GetCloses Get a list of closes
//
// Corresponds with GET /closes (the `GetCloses` operationId).
func (c *Client) GetCloses(ctx context.Context, params *GetClosesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetClosesRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetLanguageById Get a language by ID
//
// Corresponds with GET /languages/{id} (the `GetLanguageById` operationId).
func (c *Client) GetLanguageById(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetLanguageByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetUsers Get a list of users
//
// Corresponds with GET /users (the `GetUsers` operationId).
func (c *Client) GetUsers(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUsersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetUserById Get a user by ID
//
// Corresponds with GET /users/{id} (the `GetUserById` operationId).
func (c *Client) GetUserById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetUserCandidatureById Get user candidature information
//
// Corresponds with GET /users/{id}/user_candidature (the `GetUserCandidatureById` operationId).
func (c *Client) GetUserCandidatureById(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetUserCandidatureByIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetClosesRequest constructs an http.Request for the GetCloses method
func NewGetClosesRequest(server string, params *GetClosesParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/closes")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("deepObject", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Range != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("deepObject", true, "range", *params.Range, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page[number]", *params.PageNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page[size]", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetLanguageByIdRequest constructs an http.Request for the GetLanguageById method
func NewGetLanguageByIdRequest(server string, id int) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "integer", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/languages/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUsersRequest constructs an http.Request for the GetUsers method
func NewGetUsersRequest(server string, params *GetUsersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Sort != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "sort", *params.Sort, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Filter != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("deepObject", true, "filter", *params.Filter, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Range != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("deepObject", true, "range", *params.Range, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "object", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Page != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page", *params.Page, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PerPage != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "per_page", *params.PerPage, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageNumber != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page[number]", *params.PageNumber, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.PageSize != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "page[size]", *params.PageSize, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserByIdRequest constructs an http.Request for the GetUserById method
func NewGetUserByIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetUserCandidatureByIdRequest constructs an http.Request for the GetUserCandidatureById method
func NewGetUserCandidatureByIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/users/%s/user_candidature", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// GetClosesWithResponse Get a list of closes
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /closes (the `GetCloses` operationId).
	GetClosesWithResponse(ctx context.Context, params *GetClosesParams, reqEditors ...RequestEditorFn) (*GetClosesResponse, error)

	// GetLanguageByIdWithResponse Get a language by ID
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /languages/{id} (the `GetLanguageById` operationId).
	GetLanguageByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetLanguageByIdResponse, error)

	// GetUsersWithResponse Get a list of users
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /users (the `GetUsers` operationId).
	GetUsersWithResponse(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*GetUsersResponse, error)

	// GetUserByIdWithResponse Get a user by ID
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /users/{id} (the `GetUserById` operationId).
	GetUserByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetUserByIdResponse, error)

	// GetUserCandidatureByIdWithResponse Get user candidature information
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /users/{id}/user_candidature (the `GetUserCandidatureById` operationId).
	GetUserCandidatureByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetUserCandidatureByIdResponse, error)
}

type GetClosesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]CloseResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetClosesResponse) GetJSON200() *[]CloseResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetClosesResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetClosesResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetClosesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetClosesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetClosesResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetLanguageByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *LanguageResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetLanguageByIdResponse) GetJSON200() *LanguageResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetLanguageByIdResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetLanguageByIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetLanguageByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetLanguageByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetLanguageByIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetUsersResponse200Headers the declared response headers of an HTTP 200 response for GetUsers
type GetUsersResponse200Headers struct {
	Link     *string
	XPage    *int
	XPerPage *int
	XTotal   *int
}

type GetUsersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *[]LightUserResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
	// Headers200 the parsed response headers for an HTTP 200 response
	Headers200 *GetUsersResponse200Headers
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUsersResponse) GetJSON200() *[]LightUserResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetUsersResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetUsersResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUsersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUsersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUsersResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetUserByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *UserResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUserByIdResponse) GetJSON200() *UserResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetUserByIdResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetUserByIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUserByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUserByIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetUserCandidatureByIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *UserCandidatureResponse
	// JSONDefault the response for an HTTP default `application/json` response
	JSONDefault *ErrorResponse
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetUserCandidatureByIdResponse) GetJSON200() *UserCandidatureResponse {
	return r.JSON200
}

// GetJSONDefault returns the response for an HTTP default `application/json` response
func (r GetUserCandidatureByIdResponse) GetJSONDefault() *ErrorResponse {
	return r.JSONDefault
}

// GetBody returns the raw response body bytes
func (r GetUserCandidatureByIdResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetUserCandidatureByIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetUserCandidatureByIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetUserCandidatureByIdResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// GetClosesWithResponse Get a list of closes
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /closes (the `GetCloses` operationId).
func (c *ClientWithResponses) GetClosesWithResponse(ctx context.Context, params *GetClosesParams, reqEditors ...RequestEditorFn) (*GetClosesResponse, error) {
	rsp, err := c.GetCloses(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetClosesResponse(rsp)
}

// GetLanguageByIdWithResponse Get a language by ID
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /languages/{id} (the `GetLanguageById` operationId).
func (c *ClientWithResponses) GetLanguageByIdWithResponse(ctx context.Context, id int, reqEditors ...RequestEditorFn) (*GetLanguageByIdResponse, error) {
	rsp, err := c.GetLanguageById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetLanguageByIdResponse(rsp)
}

// GetUsersWithResponse Get a list of users
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /users (the `GetUsers` operationId).
func (c *ClientWithResponses) GetUsersWithResponse(ctx context.Context, params *GetUsersParams, reqEditors ...RequestEditorFn) (*GetUsersResponse, error) {
	rsp, err := c.GetUsers(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUsersResponse(rsp)
}

// GetUserByIdWithResponse Get a user by ID
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /users/{id} (the `GetUserById` operationId).
func (c *ClientWithResponses) GetUserByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetUserByIdResponse, error) {
	rsp, err := c.GetUserById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserByIdResponse(rsp)
}

// GetUserCandidatureByIdWithResponse Get user candidature information
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /users/{id}/user_candidature (the `GetUserCandidatureById` operationId).
func (c *ClientWithResponses) GetUserCandidatureByIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetUserCandidatureByIdResponse, error) {
	rsp, err := c.GetUserCandidatureById(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetUserCandidatureByIdResponse(rsp)
}

// ParseGetClosesResponse parses an HTTP response from a GetClosesWithResponse call
func ParseGetClosesResponse(rsp *http.Response) (*GetClosesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetClosesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []CloseResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetLanguageByIdResponse parses an HTTP response from a GetLanguageByIdWithResponse call
func ParseGetLanguageByIdResponse(rsp *http.Response) (*GetLanguageByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetLanguageByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LanguageResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUsersResponse parses an HTTP response from a GetUsersWithResponse call
func ParseGetUsersResponse(rsp *http.Response) (*GetUsersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUsersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest []LightUserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	switch {
	case rsp.StatusCode == 200:
		var headers GetUsersResponse200Headers
		if values := rsp.Header.Values("Link"); len(values) > 0 {
			var value string
			if err := runtime.BindStyledParameterWithOptions("simple", "Link", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""}); err != nil {
				return nil, err
			}
			headers.Link = &value
		}
		if values := rsp.Header.Values("X-Page"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Page", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.XPage = &value
		}
		if values := rsp.Header.Values("X-Per-Page"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Per-Page", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.XPerPage = &value
		}
		if values := rsp.Header.Values("X-Total"); len(values) > 0 {
			var value int
			if err := runtime.BindStyledParameterWithOptions("simple", "X-Total", values[0], &value, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "integer", Format: ""}); err != nil {
				return nil, err
			}
			headers.XTotal = &value
		}
		response.Headers200 = &headers
	}

	return response, nil
}

// ParseGetUserByIdResponse parses an HTTP response from a GetUserByIdWithResponse call
func ParseGetUserByIdResponse(rsp *http.Response) (*GetUserByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}

// ParseGetUserCandidatureByIdResponse parses an HTTP response from a GetUserCandidatureByIdWithResponse call
func ParseGetUserCandidatureByIdResponse(rsp *http.Response) (*GetUserCandidatureByIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetUserCandidatureByIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest UserCandidatureResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	}

	return response, nil
}
