ProjectLightResponse:
  type: object
  properties:
    id:
      type: integer
    name:
      type: string
    slug:
      type: string
    parent_id:
      type: integer
      nullable: true
  required:
    - id
    - name
    - slug
